#!/usr/bin/env python3
"""Adds English fallback translations of the Korean teaching notes to
assets/seed/vocab/lang/ko.json (notes.en). The seeder falls back
source-language → en, so these serve every non-French learner of Korean.
LLM-generated (Claude, 2026-08-08) pending native review."""
import json

P = '/home/thomas/vocabulary_app/assets/seed/vocab/lang/ko.json'

EN = {
 'bonjour': 'annyeonghaseyo — the standard polite greeting, usable at any time of day',
 'au-revoir-a-celui-qui-part': 'annyeonghi gaseyo — said to the person who is leaving',
 'au-revoir-a-celui-qui-reste': 'annyeonghi gyeseyo — said to the person who is staying',
 'merci': 'gamsahamnida — formal thanks, the safest choice in any situation',
 'de-rien': 'cheonmaneyo — polite, fairly formal reply to thanks',
 'pardon-excusez-moi': 'joesonghamnida — formal apology, for apologizing or getting attention',
 'donnez-moi-s-il-vous-plait': 'juseyo — placed after the thing requested: "X juseyo" = "X, please"',
 'oui': 'ne — polite yes; also used to show you are listening',
 'non': 'aniyo — polite no',
 'enchante-e': 'bangapseumnida — said when meeting someone for the first time',
 'bonne-nuit': 'annyeonghi jumuseyo — literally "sleep peacefully", honorific form',
 'd-accord-compris': 'algesseumnida — "got it", polite reply to an instruction',
 'comment-allez-vous': 'jal jinaeyo? — "how are you?", between people who know each other',
 'je-moi-forme-humble': 'jeo — humble "I / me", preferred with strangers and superiors',
 'nom': 'ireum — name, given name',
 'ami': 'chingu — friend of the same age; not used for someone older',
 'professeur': 'seonsaengnim — teacher; also serves as a respectful title',
 'personne': 'saram — person, human being; "한국 사람" = a Korean',
 'un': 'hana — native Korean numeral, for counting objects and hours',
 'deux': 'dul — native Korean numeral',
 'trois': 'set — native Korean numeral',
 'quatre': 'net — native Korean numeral',
 'cinq': 'daseot — native Korean numeral',
 'six': 'yeoseot — native Korean numeral',
 'sept': 'ilgop — native Korean numeral',
 'huit': 'yeodeol — native Korean numeral',
 'neuf': 'ahop — native Korean numeral',
 'dix': 'yeol — native Korean numeral',
 'aujourd-hui': 'oneul — today; used without a particle at the start of a sentence',
 'demain': 'naeil — tomorrow',
 'hier': 'eoje — yesterday',
 'maintenant': 'jigeum — now',
 'temps-heure-duree': 'sigan — time, duration; also "hour" in the duration sense',
 'matin': 'achim — morning; also means breakfast',
 'soir': 'jeonyeok — evening; also means dinner',
 'journee': 'haru — a whole day',
 'riz-repas': 'bap — cooked rice; also means a meal in general',
 'eau': 'mul — water',
 'kimchi': 'kimchi — spicy fermented cabbage, served with every meal',
 'viande': 'gogi — meat in general',
 'fruit': 'gwail — fruit',
 'pomme': 'sagwa — apple; also means "apology" in another context',
 'the': 'cha — tea, infusion',
 'cafe-boisson': 'keopi — coffee (loanword from English "coffee")',
 'lait': 'uyu — milk',
 'pain': 'ppang — bread (old loanword from Portuguese via Japanese)',
 'poisson-aliment': 'saengseon — fish (as food)',
 'legume': 'yachae — vegetable',
 'manger': 'meokda — to eat; stem 먹- (ends in a consonant)',
 'boire': 'masida — to drink; stem 마시- (ends in the vowel 이)',
 'delicieux': 'masitda — delicious, tasty; literally "to have taste"',
 'mauvais-au-gout': 'maseopda — bad-tasting; literally "to have no taste"',
 'avoir-faim': 'baegopeuda — to be hungry; an adjective in Korean, conjugated like a stative verb',
 'restaurant': 'sikdang — restaurant, canteen; usually simple Korean food',
 'maison': 'jip — house, home',
 'ecole': 'hakgyo — school',
 'entreprise-bureau': 'hoesa — company, office (place of work)',
 'dormir': 'jada — to sleep; stem 자- (vowel 아)',
 'se-lever': 'ireonada — to get up, to wake up',
 'aller': 'gada — to go; stem 가- (vowel 아), contraction 가 + 아요 → 가요',
 'venir': 'oda — to come; stem 오- (vowel 오), contraction 오 + 아요 → 와요',
 'voir-regarder': 'boda — to see, to watch; contraction 보 + 아요 → 봐요',
 'faire': 'hada — to do; the most frequent irregular verb: 하다 → 해요',
 'etudier': 'gongbuhada — to study; a 하다 verb, so 공부해요 in the present',
 'travailler': 'ilhada — to work; a 하다 verb, so 일해요 in the present',
 'lire': 'ikda — to read; stem 읽- (ends in a consonant)',
 'acheter': 'sada — to buy; stem 사- (vowel 아), so 사요',
 'ecouter': 'deutda — to listen, to hear; ㄷ-irregular: 듣다 → 들어요',
 'aimer-apprecier': 'joahada — to like, to enjoy; a 하다 verb, so 좋아해요',
 'vivre-habiter': 'salda — to live; ㄹ-irregular in some forms, but 살아요 in the present',
 'livre': 'chaek — book',
 'telephone-portable': 'haendeupon — cell phone (from English "hand" + "phone")',
 'etudiant': 'haksaeng — student, pupil',
 'etre-occupe': 'bappeuda — to be busy; ㅡ-irregular: 바쁘다 → 바빠요',
 'metro': 'jihacheol — subway',
 'bus': 'beoseu — bus (loanword from English)',
 'taxi': 'taeksi — taxi (loanword from English)',
 'train': 'gicha — train',
 'rue-chemin': 'gil — street, way',
 'gare-station': 'yeok — train or subway station',
 'aeroport': 'gonghang — airport',
 'coree': 'hanguk — (South) Korea',
 'france': 'peurangseu — France',
 'seoul': 'seoul — Seoul, capital of South Korea',
 'paris': 'pari — Paris',
 'ici': 'yeogi — here',
 'la-bas': 'jeogi — over there (far from both speaker and listener)',
 'ou': 'eodi — where; used like an interrogative noun',
 'marcher': 'geotda — to walk; ㄷ-irregular: 걷다 → 걸어요',
 'prendre-un-transport': 'tada — to take (transport), to get on; stem 타- (vowel 아)',
 'descendre-d-un-transport': 'naerida — to get off (transport)',
 'arriver': 'dochakhada — to arrive; a 하다 verb, so 도착해요',
 'partir': 'chulbalhada — to leave, to depart; a 하다 verb, so 출발해요',
 'aider': 'dopda — to help; ㅂ-irregular: 돕다 → 도와요',
 'ko-particule-de-theme-apres-consonne': 'eun — topic particle after a final consonant (batchim)',
 'ko-particule-de-theme-apres-voyelle': 'neun — topic particle after a vowel',
 'ko-particule-de-sujet-apres-consonne': 'i — subject particle after a final consonant (batchim)',
 'ko-particule-de-sujet-apres-voyelle': 'ga — subject particle after a vowel',
 'ko-particule-d-objet-apres-consonne': 'eul — direct-object particle after a final consonant (batchim)',
 'ko-particule-d-objet-apres-voyelle': 'reul — direct-object particle after a vowel',
 'ko-a-vers-destination-temps': 'e — particle for destination ("to, toward") and time ("at, on")',
 'ko-a-dans-lieu-d-action': 'eseo — particle for where an action happens ("at, in") or origin ("from")',
 'ko-aussi': 'do — "also, too"; replaces 은/는 and 이/가',
 'ko-et-avec-apres-voyelle': 'wa — "and / with" after a vowel (written or careful register)',
 'ko-et-avec-apres-consonne': 'gwa — "and / with" after a final consonant (written or careful register)',
 'ko-et-avec-oral': 'hago — "and / with" in speech, one form regardless of the ending',
 'ko-de-possession': 'ui — possession particle ("of"); often pronounced "e"',
 'ko-a-partir-de-depuis': 'buteo — "from, since" (starting time or place)',
 'ko-jusqu-a': 'kkaji — "until, up to" (ending time or place)',
 'ko-seulement': 'man — "only, nothing but"',
 'ko-ne-pas-negation': 'an — negation adverb, placed right before the verb or adjective',
}

ko = json.load(open(P))
missing = [k for k in ko['entries'] if k not in EN]
assert not missing, missing
for cid, entry in ko['entries'].items():
    entry.setdefault('notes', {})['en'] = EN[cid]
with open(P, 'w') as f:
    json.dump(ko, f, ensure_ascii=False, indent=2)
    f.write('\n')
print('en notes:', len(EN))
